package be.valuya.lombok.optionalgetter.idea

import com.intellij.lang.java.JavaLanguage
import com.intellij.openapi.util.RecursionManager
import com.intellij.psi.JavaPsiFacade
import com.intellij.psi.PsiClass
import com.intellij.psi.PsiCompiledElement
import com.intellij.psi.PsiElement
import com.intellij.psi.PsiMethod
import com.intellij.psi.PsiModifier
import com.intellij.psi.PsiTypeParameter
import com.intellij.psi.augment.PsiAugmentProvider
import com.intellij.psi.impl.light.LightMethodBuilder
import com.intellij.psi.util.CachedValueProvider
import com.intellij.psi.util.CachedValuesManager
import com.intellij.psi.util.PsiModificationTracker

/**
 * Teaches IntelliJ about the accessors generated by `@lombok.OptionalGetter` (from the
 * `io.github.valuya:lombok` overlay), so `getXxxOptional()` resolves in the editor: code completion,
 * find-usages and go-to-declaration all work, and the calls stop showing as unresolved.
 *
 * This is the same mechanism the bundled Lombok plugin uses for `@Getter` etc. — it injects synthetic
 * `PsiMethod`s into the class model; it does not run the real annotation processor.
 */
class OptionalGetterAugmentProvider : PsiAugmentProvider() {

    override fun <Psi : PsiElement> getAugments(element: PsiElement, type: Class<Psi>, nameHint: String?): List<Psi> {
        if (type != PsiMethod::class.java) return emptyList()
        if (element !is PsiClass || element is PsiTypeParameter || element is PsiCompiledElement) return emptyList()
        val psiClass = element
        if (psiClass.name == null) return emptyList()

        val cached: List<PsiMethod> = CachedValuesManager.getCachedValue(psiClass) {
            val methods = RecursionManager.doPreventingRecursion(psiClass, false) { buildOptionalGetters(psiClass) }
                ?: emptyList()
            CachedValueProvider.Result.create(methods, PsiModificationTracker.MODIFICATION_COUNT)
        }

        val selected = if (nameHint == null) cached else cached.filter { it.name == nameHint }
        @Suppress("UNCHECKED_CAST")
        return selected as List<Psi>
    }

    private fun buildOptionalGetters(psiClass: PsiClass): List<PsiMethod> {
        val factory = JavaPsiFacade.getElementFactory(psiClass.project)
        val methods = ArrayList<PsiMethod>()
        for (field in psiClass.fields) {
            if (!OptionalGetterSupport.appliesTo(field)) continue
            // Return type mirrors the runtime: Optional<T> without the field's nullness annotations.
            val returnType = factory.createTypeFromText(
                "java.util.Optional<" + field.type.getCanonicalText(false) + ">", field
            )
            val method = LightMethodBuilder(psiClass.manager, JavaLanguage.INSTANCE, OptionalGetterSupport.getterName(field))
                .setContainingClass(psiClass)
                .setMethodReturnType(returnType)
                .addModifier(PsiModifier.PUBLIC)
            method.navigationElement = field
            method.setOriginInfo("generated by @OptionalGetter")
            methods.add(method)
        }
        return methods
    }
}
